const portfolioData = {
    personalInfo: {
        name: 'Yash Mayurkumar Soni',
        shortName: 'Yash Soni',
        initials: 'YS',
        role: 'Frontend Developer',
        roles: ['Frontend Developer', 'React Developer', 'UI/UX Enthusiast', 'Problem Solver'],
        summary: 'Frontend Developer passionate about crafting clean, responsive, and interactive web experiences. Skilled in building user-friendly interfaces that combine functionality with modern design.',
        location: 'Anand, Gujarat, India',
        phone: '+91 9313083522',
        email: '75soniyashmayurkumar@gmail.com',
        github: 'https://github.com/yashsoni972',
        linkedin: 'https://www.linkedin.com/in/yash-soni-b46682355/',
        resume: './YASH_SONI_RESUME.pdf',
        objective: 'To secure a challenging Frontend Developer role where I can apply my skills in modern web technologies, contribute to impactful projects, and continuously grow as a software developer.',
    },

    skills: {
        'Languages': [
            { name: 'HTML5',      icon: 'fa-html5' },
            { name: 'CSS3',       icon: 'fa-css3' },
            { name: 'JavaScript', icon: 'fa-js-square' },
            { name: 'Python',     icon: 'fa-python' },
        ],
        'Frameworks & Libraries': [
            { name: 'React.js',    icon: 'fa-react' },
            { name: 'Tailwind CSS',icon: 'fa-tailwind' },
        ],
        'Tools & Platforms': [
            { name: 'Git',    icon: 'fa-git' },
            { name: 'GitHub', icon: 'fa-github' },
            { name: 'VS Code',icon: 'fa-code' },
        ],
        'Databases': [
            { name: 'MySQL',   icon: 'fa-database' },
            { name: 'MongoDB', icon: 'fa-leaf' },
        ],
    },

    projects: [
        {
            id: 'citysolve',
            title: 'CitySolve',
            subtitle: 'Smart Civic Platform',
            description: 'An innovative civic technology platform bridging the gap between citizens and local authorities. Enables users to report urban issues and track resolutions efficiently.',
            features: ['Know Your District', 'Live Map Reporting', 'Issue Reporting with Pins', 'Contractor Management Module', 'Analytics Dashboard', 'Smart Notification System'],
            tags: ['HTML', 'CSS', 'JavaScript', 'Civic Tech'],
            demo: 'https://citysolve.me/',
            github: null,
            badge: '🏆 Hackathon Winner',
            icon: '🏙️',
        },
        {
            id: 'gallery-hub',
            title: 'Gallery Hub',
            subtitle: 'Image Gallery Platform',
            description: 'A responsive web-based gallery platform that allows users to explore and manage images with a clean and modern UI design.',
            features: ['Responsive Grid Layout', 'Image Management', 'Modern UI', 'Smooth Animations'],
            tags: ['HTML', 'CSS', 'JavaScript', 'Responsive'],
            demo: 'https://yashsoni972.github.io/CodeAlpha_Gallery_Hub/',
            github: 'https://github.com/yashsoni972/CodeAlpha_Gallery_Hub',
            badge: null,
            icon: '🖼️',
        },
        {
            id: 'calculator-pro',
            title: 'Calculator Pro',
            subtitle: 'Scientific Calculator',
            description: 'An advanced calculator web application with scientific functionalities and an intuitive interface. Designed for accuracy and ease of use.',
            features: ['Scientific Functions', 'Intuitive Interface', 'Accurate Calculations', 'Keyboard Support'],
            tags: ['HTML', 'CSS', 'JavaScript', 'Scientific'],
            demo: 'https://yashsoni972.github.io/CodeAlpha_Calculator-Pro/',
            github: 'https://github.com/yashsoni972/CodeAlpha_Calculator-Pro',
            badge: null,
            icon: '🧮',
        },
    ],

    experience: [
        {
            type: 'internship',
            title: 'Frontend Developer Intern',
            company: 'CodeAlpha',
            period: '2026',
            badge: 'Virtual • Completed',
            description: 'Completed frontend development projects during the internship. Built Image Gallery, Calculator Pro, and Portfolio as part of the program. Gained hands-on experience in building responsive, interactive web applications.',
            projects: ['🖼️ Image Gallery', '🧮 Calculator Pro', '🗂️ Portfolio'],
            tags: ['HTML', 'CSS', 'JavaScript', 'GitHub'],
        },
        {
            type: 'hackathon',
            title: '1st Place — Hackathon Winner 🥇',
            company: 'CitySolve — Smart Citizen Reporting System',
            period: '2026',
            description: 'Won 1st position in a competitive hackathon by building CitySolve — a full-stack civic technology platform.',
            contributions: [
                'Developed "Know Your District" feature',
                'Designed frontend layout and UI/UX',
                'Integrated data analysis on frontend',
                'Built categorized email notification system',
                'Structured responsive design and layouts',
            ],
            tags: ['React', 'Civic Tech', 'UI/UX', 'Full Stack'],
        },
    ],

    education: [
        {
            degree: 'B.Tech — Computer Engineering',
            institute: 'CVM University, Gujarat',
            period: '2023 — Present',
            icon: '🎓',
            subjects: ['Web Development', 'Data Structures', 'Python', 'Java', 'DBMS', 'OS', 'Computer Networks'],
            description: 'Currently in 3rd year. Core subjects include C, C++, Data Structures, DBMS, Java, OS, Computer Networks, Computer Graphics, COA, DAA, Python, Web Development, and Software Engineering.',
        },
        {
            degree: 'Higher Secondary (12th Science — PCM)',
            institute: 'R.P.T.P Science Stream',
            period: '12th Standard',
            icon: '📚',
            subjects: ['Physics', 'Chemistry', 'Mathematics', 'Computer Science'],
            description: 'Completed 12th Science with Physics, Chemistry, Mathematics, and Computer Science.',
        },
        {
            degree: 'Secondary Education (10th)',
            institute: 'Maganbhai Umedbhai Patel Technical High School',
            period: '10th Standard',
            icon: '🏫',
            subjects: ['Mathematics', 'Science', 'Computer Science', 'Technical'],
            description: 'Strong foundation in Mathematics, Science, Computer Science, and Technical subjects.',
        },
    ],

    chatbotKnowledge: {
        skills: 'Yash is skilled in:\n• Languages: HTML, CSS, JavaScript, Python\n• Frameworks: React.js, Tailwind CSS\n• Tools: Git, GitHub, VS Code\n• Databases: MySQL, MongoDB',
        projects: 'Yash has built 3 projects:\n1. 🏙️ CitySolve — Smart Civic Platform (Hackathon Winner)\n   Demo: https://citysolve.me/\n2. 🖼️ Gallery Hub — Image Gallery Platform\n   Demo: https://yashsoni972.github.io/CodeAlpha_Gallery_Hub/\n3. 🧮 Calculator Pro — Scientific Calculator\n   Demo: https://yashsoni972.github.io/CodeAlpha_Calculator-Pro/',
        experience: "Yash's experience:\n• Frontend Developer Intern at CodeAlpha (Virtual)\n• 🏆 1st Place Hackathon Winner for CitySolve",
        education: "Yash's education:\n• B.Tech Computer Engineering — CVM University (2023–Present)\n• 12th Science (PCM) — R.P.T.P Science Stream\n• 10th — Maganbhai Umedbhai Patel Technical High School",
        contact: 'You can reach Yash at:\n• 📞 Phone: +91 9313083522\n• 📧 Email: 75soniyashmayurkumar@gmail.com\n• 💼 LinkedIn: linkedin.com/in/yash-soni-b46682355\n• 🐙 GitHub: github.com/yashsoni972',
        about: "Yash Mayurkumar Soni is a Frontend Developer from Anand, Gujarat, India. He's passionate about crafting clean, responsive, and interactive web experiences. Currently pursuing B.Tech in Computer Engineering at CVM University.",
        resume: 'Yash\'s resume is available! You can download it in the Resume section, or contact him at 75soniyashmayurkumar@gmail.com',
        citysolve: 'CitySolve is Yash\'s flagship project — a Smart Civic Platform that won 1st place in a hackathon!\n\nFeatures: Live Map Reporting, Analytics Dashboard, Smart Notifications, Contractor Management.\n\nLive: https://citysolve.me/',
        hire: 'Yash is open to Frontend Developer roles and internships! Contact him at:\n📧 75soniyashmayurkumar@gmail.com\n💼 linkedin.com/in/yash-soni-b46682355',
    },
};
